### ISSUE TITLE
Bring this repo back to life!

### ISSUE THREAD

**Issue by joeapearson** [ankhers/mongodb#365]
There are a number of things I believe we need to do to bring this repo back to life for the community:

- [x] Restore some kind of CI solution for continuous testing + validation against various versions of Mongo.  I suggest GitHub Actions.  We'll also need to decide which versions of Mongo and OTP will be "officially supported".
- [x] Post CI, update developer / contributing docs so that devs can run the same tests (or a subset thereof) on a local machine.
- [x] Merge in the latest PRs, especially #364 which has the side effect of addressing some other reported issues
- [ ] Go through the issues triage / close as needed
- [ ] Go through the other PRs, triage / close as needed
- [x] Add / revise a CONTRIBUTING.md document to let devs know how to get up and running to make changes

There is plenty to do but I'd like to keep this particular issue in the scope of "project revival".  We can look at other issues, bugs, feature requests and so on as separate issues.

I'm happy to take on the GitHub actions + developer contributing instructions work.

Please suggest anything else you think might be needed!

**Comment by scottmessinger** [comment]
These look awesome! If you could take the CI & dev contributing instructions, I can  take care of getting the PRs merged in and triaging the issues/PRs!

**Comment by joeapearson** [comment]
Thanks Scott.  I realised we probably need to decide which versions of Mongo and OTP will be officially supported going forward.  I suggest:

* Mongo v4 latest and newer (although there might be extra work involved in supporting Mongo v5, not sure)
* OTP v23 and newer

**Comment by scottmessinger** [comment]
Those sound great to me! We're on Mongo 4.0.26 in production. We'll likely upgrade to 4.2 or 4.4 this winter. 

As for Elixir, we're on OTP 23.2 and Elixir 1.11.4.

So, Mongo 4 and OTP v23 sound great and doable!

**Comment by joeapearson** [comment]
Alright that sounds good.  I suggest we don't go out of our way to deprecate older versions but users that need it will either need to use an older version of this package or "at your own risk".

**Comment by ankhers** [comment]
I have already mentioned it to Scott but I'll say it here too. I don't
actually use mongo anymore, but if there is anything I can do to help,
let me know and I will do what I can.

**Comment by fireproofsocks** [comment]
I'd like to help out here if possible.  Given the target items listed above, is there any way to evaluate which tickets (new or existing) should be given priority treatment?

**Comment by joeapearson** [comment]
@fireproofsocks excellent and yes please!  I think best thing is for us to get a basic Ecto 3 support merged into master, we cut a beta release, and then we go to town on fixes / improvements and so on.  Otherwise I think we're going to end up with a merge nightmare.

**Comment by scottmessinger** [comment]
@fireproofsocks Awesome! I think the biggest need right now is to get our CI setup on github actions working -- is that right, @joeapearson ?

**Comment by scottmessinger** [comment]
@joeapearson To coordinate, I created a project with everything I think we've listed so far. 

https://github.com/elixir-mongo/mongodb/projects/1

I think we're good to cut a beta.1 release, no? Obviously, we need to do more to get this live, but since it supports ecto 3, seems like we can cut that release and start having people testing it. Let me know your thoughts!

**Comment by joeapearson** [comment]
Excellent.  Yes I think we want the CI in place ASAP so we can accept contributions with confidence.  I'm working on it in #370 . At least two issues are going to fall out of that work.  There are the other outstanding issues too, which are in varying states of repair themselves (some of them are very old and I'm not sure relevant any more).  These need going through too.

**Comment by fireproofsocks** [comment]
I think it's important to have support for AWS DocDB too... that's tough write tests against, but DocDB is likely going to be the version of "mongo" in many setups.

**Comment by joeapearson** [comment]
@fireproofsocks sure; let's keep that separate though.  There is #273 already open but perhaps you might like to create a new issue and/or discussion to cover that.

**Comment by joeapearson** [comment]
Basic CI is ready in #370 pending Scott's review.  PRs welcome for everything else.  Have to go back to my proper job for a while :) .

**Comment by scottmessinger** [comment]
@joeapearson It took forever, but I published 1.0 and merged in your CI branch! Thanks!!!

**Comment by scottmessinger** [comment]
@joeapearson The one regret I have is we didn't find a way to make the changes to find_one_and_update non-breaking. I took a look at it before pushing 1.0 and I wasn't sure an easy path to making the change.

Frankly, I think the next step is actually to retire this driver and change the mongodb_ecto driver to use @zookzook's. I'm not sure how we'll do that, but I think that's a more sustainable path long term.
